---
- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  
  # pre_tasks:
  #   - name: "wait 210 seconds for target connection to become reachable/usable."
  #     wait_for:
  #       host: web
  #       port: 22       
  #       delay: 210
  #       timeout: 0
  roles:
    - configure-server
    - configure-prometheus-node-exporter